compilation:
  cloud_properties: {}
  network: compilation
  reuse_compilation_vms: true
  workers: 6
director_uuid: b02f8ab5-b63c-4f08-b144-89f96810a022
jobs:
- instances: 1
  name: etcd_z1
  networks:
  - name: default
    static_ips:
    - 10.244.0.42
  persistent_disk: 10024
  properties:
    metron_agent:
      zone: z1
    networks:
      apps: default
  resource_pool: default
  templates:
  - name: etcd
    release: etcd
  - name: etcd_metrics_server
    release: etcd
  - name: metron_agent
    release: lamb
  update:
    max_in_flight: 1
name: etcd
networks:
- name: compilation
  subnets:
  - cloud_properties: {}
    range: 10.244.1.0/30
    reserved:
    - 10.244.1.1
  - cloud_properties: {}
    range: 10.244.1.4/30
    reserved:
    - 10.244.1.5
  - cloud_properties: {}
    range: 10.244.1.8/30
    reserved:
    - 10.244.1.9
  - cloud_properties: {}
    range: 10.244.1.12/30
    reserved:
    - 10.244.1.13
  - cloud_properties: {}
    range: 10.244.1.16/30
    reserved:
    - 10.244.1.17
  - cloud_properties: {}
    range: 10.244.1.20/30
    reserved:
    - 10.244.1.21
  - cloud_properties: {}
    range: 10.244.1.24/30
    reserved:
    - 10.244.1.25
  - cloud_properties: {}
    range: 10.244.1.28/30
    reserved:
    - 10.244.1.29
  - cloud_properties: {}
    range: 10.244.1.32/30
    reserved:
    - 10.244.1.33
  - cloud_properties: {}
    range: 10.244.1.36/30
    reserved:
    - 10.244.1.37
  - cloud_properties: {}
    range: 10.244.1.40/30
    reserved:
    - 10.244.1.41
  - cloud_properties: {}
    range: 10.244.1.44/30
    reserved:
    - 10.244.1.45
- name: default
  subnets:
  - cloud_properties: {}
    range: 10.244.0.12/30
    reserved:
    - 10.244.0.13
  - cloud_properties: {}
    range: 10.244.0.40/30
    reserved:
    - 10.244.0.41
    static:
    - 10.244.0.42
properties:
  etcd:
    machines:
    - 10.244.0.42
  etcd_metrics_server:
    nats:
      machines:
      - 10.244.0.6
      password: nats
      username: nats
  loggregator_endpoint:
    shared_secret: PLACEHOLDER-LOGGREGATOR-SECRET
  metron_agent:
    deployment: foo
  nats:
    machines:
    - 10.244.0.6
    password: nats
    port: 4222
    user: nats
releases:
- name: etcd
  version: latest
- name: lamb
  version: latest
resource_pools:
- cloud_properties: {}
  name: default
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 50
  serial: true
  update_watch_time: 1000-180000

