compilation:
  cloud_properties: {}
  network: compilation
  reuse_compilation_vms: true
  workers: 6
director_uuid: b02f8ab5-b63c-4f08-b144-89f96810a022
jobs:
- instances: 1
  name: uaa_z1
  networks:
  - name: default
  properties:
    consul:
      agent:
        services:
          uaa: {}
    metron_agent:
      zone: z1
    networks:
      apps: default
  resource_pool: default
  templates:
  - name: uaa
    release: identity
  - name: metron_agent
    release: lamb
  - name: consul_agent
    release: consul
name: identity
networks:
- name: compilation
  subnets:
  - cloud_properties: {}
    range: 10.244.1.0/30
    reserved:
    - 10.244.1.1
  - cloud_properties: {}
    range: 10.244.1.4/30
    reserved:
    - 10.244.1.5
  - cloud_properties: {}
    range: 10.244.1.8/30
    reserved:
    - 10.244.1.9
  - cloud_properties: {}
    range: 10.244.1.12/30
    reserved:
    - 10.244.1.13
  - cloud_properties: {}
    range: 10.244.1.16/30
    reserved:
    - 10.244.1.17
  - cloud_properties: {}
    range: 10.244.1.20/30
    reserved:
    - 10.244.1.21
  - cloud_properties: {}
    range: 10.244.1.24/30
    reserved:
    - 10.244.1.25
  - cloud_properties: {}
    range: 10.244.1.28/30
    reserved:
    - 10.244.1.29
  - cloud_properties: {}
    range: 10.244.1.32/30
    reserved:
    - 10.244.1.33
  - cloud_properties: {}
    range: 10.244.1.36/30
    reserved:
    - 10.244.1.37
  - cloud_properties: {}
    range: 10.244.1.40/30
    reserved:
    - 10.244.1.41
  - cloud_properties: {}
    range: 10.244.1.44/30
    reserved:
    - 10.244.1.45
- name: default
  subnets:
    - cloud_properties: {}
      range: 10.244.0.16/30
      reserved:
        - 10.244.0.17
properties:
  consul:
    agent:
      log_level: null
      servers:
        lan:
        - 10.244.0.54
  domain: 10.244.0.34.xip.io
  etcd:
    machines:
    - 10.244.0.42
  loggregator_endpoint:
    shared_secret: PLACEHOLDER-LOGGREGATOR-SECRET
  login:
    analytics:
      code: null
      domain: null
    asset_base_url: null
    brand: oss
    catalina_opts: null
    domain: 10.244.0.34.xip.io
    enabled: true
    invitations_enabled: null
    links:
      home: https://console.10.244.0.34.xip.io
      network: null
      passwd: https://console.10.244.0.34.xip.io/password_resets/new
      signup: https://console.10.244.0.34.xip.io/register
      signup-network: null
    logout: null
    messages: null
    notifications:
      url: null
    protocol: http
    restricted_ips_regex: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}
    saml: null
    self_service_links_enabled: null
    signups_enabled: null
    smtp:
      host: null
      password: null
      port: null
      user: null
    spring_profiles: null
    tiles: null
    uaa_base: null
    uaa_certificate: |+
      -----BEGIN CERTIFICATE-----
      MIIDETCCAfmgAwIBAgIJANZuykf1uh3LMA0GCSqGSIb3DQEBBQUAMB8xHTAbBgNV
      BAMMFCouMTAuMjQ0LjAuMzQueGlwLmlvMB4XDTE0MTIyNDIzMTkxM1oXDTI0MTIy
      MTIzMTkxM1owHzEdMBsGA1UEAwwUKi4xMC4yNDQuMC4zNC54aXAuaW8wggEiMA0G
      CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCjq73Fgwfj2UT0/+wR9kVVsGAguMj
      poA0opLCgE0yHStAhSvqq7YpO39dH3vBMWXyr2xIfDyaeZyhV86jWu/ZKswGjNGI
      ZKv/yUINe1bqukOBqd+SHVvkVhxSLJuD1MR83JQMONRjOPJp661/ABpVhnrNfBiA
      AA6aaFv4/KbyGY/E1FHoUXqEdh4WxaJdfX6SbgG05ArWxhSD7PNj4CYvJWGCdvqP
      KBsvWFDrkxBHn5h1JIDfZJB8FKP6vaHBr7MU4pIHM+qaZ1Y+8ja0wcgkHn4YHcp6
      IOhqpck7LaH5Qq2ydYFNTcG4fTbG0jXqcit2WSUxRkXzWnrgo2E0SiHBAgMBAAGj
      UDBOMB0GA1UdDgQWBBSpCtEDtEvMwaZzXN6Lvk5U7Eyn2zAfBgNVHSMEGDAWgBSp
      CtEDtEvMwaZzXN6Lvk5U7Eyn2zAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUA
      A4IBAQB1YIHmw3gPiMn8WDR4yVxDvSVgFHY6ZE1iZb17vVs4N2/mhQZXWJ2nZV02
      goAivtgxHOj39sK5OBWsGvrQo5H8dt1t4XmbwB1C6xRerGc25dhDRq42RqhCN0RJ
      zzjd9b8YSiwtAaZlW36l2jVDLfRapb00tWToF9qYrDrmKy2sekS7g2hbiRStcue/
      bpT4X/CHxb/lUbpL4m8BpDbkGiOJgl+SEHRx5tZ0Kob/RDQRCcN3p+71FRbDIEBj
      +8sJl/yUUUPwQ6PNYx6cjtlICWJ1G0l0hRa141VXPqSNCmxYS4dp/8ifPCSoLc+k
      9TXFkuGl+86CPTyyMJxyMhEcAGZT
      -----END CERTIFICATE-----
    url: null
  metron_agent:
    deployment: foo
  nats:
    machines:
    - 10.244.0.6
    password: nats
    port: 4222
    user: nats
  uaa:
    admin:
      client_secret: admin-secret
    authentication:
      policy:
        countFailuresWithinSeconds: null
        lockoutAfterFailures: null
        lockoutPeriodSeconds: null
    batch:
      password: batch-password
      username: batch-username
    catalina_opts: -Xmx192m -XX:MaxPermSize=128m
    cc:
      client_secret: cc-secret
    clients:
      app-direct:
        access-token-validity: 1209600
        authorities: app_direct_invoice.write
        authorized-grant-types: authorization_code,client_credentials,password,refresh_token,implicit
        override: true
        redirect-uri: https://console.10.244.0.34.xip.io
        refresh-token-validity: 1209600
        secret: app-direct-secret
      cc-service-dashboards:
        authorities: clients.read,clients.write,clients.admin
        authorized-grant-types: client_credentials
        scope: openid,cloud_controller_service_permissions.read
        secret: cc-broker-secret
      cloud_controller_username_lookup:
        authorities: scim.userids
        authorized-grant-types: client_credentials
        secret: cloud-controller-username-lookup-secret
      developer_console:
        access-token-validity: 1209600
        authorities: scim.write,scim.read,cloud_controller.read,cloud_controller.write,password.write,uaa.admin,uaa.resource,cloud_controller.admin,billing.admin
        authorized-grant-types: authorization_code,client_credentials
        override: true
        redirect-uri: https://console.10.244.0.34.xip.io/oauth/callback
        refresh-token-validity: 1209600
        scope: openid,cloud_controller.read,cloud_controller.write,password.write,console.admin,console.support
        secret: console-secret
      doppler:
        authorities: uaa.resource
        override: true
        secret: doppler-secret
      gorouter:
        authorities: clients.read,clients.write,clients.admin,route.admin,route.advertise
        authorized-grant-types: client_credentials,refresh_token
        scope: openid,cloud_controller_service_permissions.read
        secret: gorouter-secret
      login:
        authorities: oauth.login,scim.write,clients.read,notifications.write,critical_notifications.write,emails.write,scim.userids,password.write
        authorized-grant-types: authorization_code,client_credentials,refresh_token
        override: true
        redirect-uri: http://login.10.244.0.34.xip.io
        scope: openid,oauth.approvals
        secret: login-secret
      notifications:
        authorities: cloud_controller.admin,scim.read
        authorized-grant-types: client_credentials
        secret: notification-secret
    database: null
    issuer: https://uaa.10.244.0.34.xip.io
    jwt:
      signing_key: |+
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQDHFr+KICms+tuT1OXJwhCUmR2dKVy7psa8xzElSyzqx7oJyfJ1
        JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMXqHxf+ZH9BL1gk9Y6kCnbM5R6
        0gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBugspULZVNRxq7veq/fzwIDAQAB
        AoGBAJ8dRTQFhIllbHx4GLbpTQsWXJ6w4hZvskJKCLM/o8R4n+0W45pQ1xEiYKdA
        Z/DRcnjltylRImBD8XuLL8iYOQSZXNMb1h3g5/UGbUXLmCgQLOUUlnYt34QOQm+0
        KvUqfMSFBbKMsYBAoQmNdTHBaz3dZa8ON9hh/f5TT8u0OWNRAkEA5opzsIXv+52J
        duc1VGyX3SwlxiE2dStW8wZqGiuLH142n6MKnkLU4ctNLiclw6BZePXFZYIK+AkE
        xQ+k16je5QJBAN0TIKMPWIbbHVr5rkdUqOyezlFFWYOwnMmw/BKa1d3zp54VP/P8
        +5aQ2d4sMoKEOfdWH7UqMe3FszfYFvSu5KMCQFMYeFaaEEP7Jn8rGzfQ5HQd44ek
        lQJqmq6CE2BXbY/i34FuvPcKU70HEEygY6Y9d8J3o6zQ0K9SYNu+pcXt4lkCQA3h
        jJQQe5uEGJTExqed7jllQ0khFJzLMx0K6tj0NeeIzAaGCQz13oo2sCdeGRHO4aDh
        HH6Qlq/6UOV5wP8+GAcCQFgRCcB+hrje8hfEEefHcFpyKH+5g1Eu1k0mLrxK2zd+
        4SlotYRHgPCEubokb2S1zfZDWIXW3HmggnGgM949TlY=
        -----END RSA PRIVATE KEY-----
      verification_key: |+
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHFr+KICms+tuT1OXJwhCUmR2d
        KVy7psa8xzElSyzqx7oJyfJ1JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMX
        qHxf+ZH9BL1gk9Y6kCnbM5R60gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBug
        spULZVNRxq7veq/fzwIDAQAB
        -----END PUBLIC KEY-----
    ldap: null
    login: null
    newrelic: null
    no_ssl: true
    restricted_ips_regex: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}
    scim:
      external_groups: null
      userids_enabled: true
      users:
      - admin|admin|scim.write,scim.read,openid,cloud_controller.admin,clients.read,clients.write,doppler.firehose
    spring_profiles: null
    url: https://uaa.10.244.0.34.xip.io
    user: null
    zones: null
  uaadb:
    address: 10.244.0.30
    databases:
    - citext: true
      name: uaadb
      tag: uaa
    db_scheme: postgresql
    port: 5524
    roles:
    - name: uaaadmin
      password: admin
      tag: admin
releases:
- name: identity
  version: latest
- name: consul
  version: latest
- name: lamb
  version: latest
resource_pools:
- cloud_properties: {}
  name: default
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 50
  serial: true
  update_watch_time: 1000-180000

