compilation:
  cloud_properties: {}
  network: compilation
  reuse_compilation_vms: true
  workers: 6
director_uuid: b02f8ab5-b63c-4f08-b144-89f96810a022
jobs:
- default_networks:
  - name: default
    static_ips: null
  instances: 1
  name: ha_proxy_z1
  networks:
  - name: default
    static_ips:
    - 10.244.0.34
  properties:
    ha_proxy:
      disable_http: false
      ssl_ciphers: null
      ssl_pem: |+
        -----BEGIN CERTIFICATE-----
        MIIDETCCAfmgAwIBAgIJANZuykf1uh3LMA0GCSqGSIb3DQEBBQUAMB8xHTAbBgNV
        BAMMFCouMTAuMjQ0LjAuMzQueGlwLmlvMB4XDTE0MTIyNDIzMTkxM1oXDTI0MTIy
        MTIzMTkxM1owHzEdMBsGA1UEAwwUKi4xMC4yNDQuMC4zNC54aXAuaW8wggEiMA0G
        CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCjq73Fgwfj2UT0/+wR9kVVsGAguMj
        poA0opLCgE0yHStAhSvqq7YpO39dH3vBMWXyr2xIfDyaeZyhV86jWu/ZKswGjNGI
        ZKv/yUINe1bqukOBqd+SHVvkVhxSLJuD1MR83JQMONRjOPJp661/ABpVhnrNfBiA
        AA6aaFv4/KbyGY/E1FHoUXqEdh4WxaJdfX6SbgG05ArWxhSD7PNj4CYvJWGCdvqP
        KBsvWFDrkxBHn5h1JIDfZJB8FKP6vaHBr7MU4pIHM+qaZ1Y+8ja0wcgkHn4YHcp6
        IOhqpck7LaH5Qq2ydYFNTcG4fTbG0jXqcit2WSUxRkXzWnrgo2E0SiHBAgMBAAGj
        UDBOMB0GA1UdDgQWBBSpCtEDtEvMwaZzXN6Lvk5U7Eyn2zAfBgNVHSMEGDAWgBSp
        CtEDtEvMwaZzXN6Lvk5U7Eyn2zAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUA
        A4IBAQB1YIHmw3gPiMn8WDR4yVxDvSVgFHY6ZE1iZb17vVs4N2/mhQZXWJ2nZV02
        goAivtgxHOj39sK5OBWsGvrQo5H8dt1t4XmbwB1C6xRerGc25dhDRq42RqhCN0RJ
        zzjd9b8YSiwtAaZlW36l2jVDLfRapb00tWToF9qYrDrmKy2sekS7g2hbiRStcue/
        bpT4X/CHxb/lUbpL4m8BpDbkGiOJgl+SEHRx5tZ0Kob/RDQRCcN3p+71FRbDIEBj
        +8sJl/yUUUPwQ6PNYx6cjtlICWJ1G0l0hRa141VXPqSNCmxYS4dp/8ifPCSoLc+k
        9TXFkuGl+86CPTyyMJxyMhEcAGZT
        -----END CERTIFICATE-----
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAwo6u9xYMH49lE9P/sEfZFVbBgILjI6aANKKSwoBNMh0rQIUr
        6qu2KTt/XR97wTFl8q9sSHw8mnmcoVfOo1rv2SrMBozRiGSr/8lCDXtW6rpDganf
        kh1b5FYcUiybg9TEfNyUDDjUYzjyaeutfwAaVYZ6zXwYgAAOmmhb+Pym8hmPxNRR
        6FF6hHYeFsWiXX1+km4BtOQK1sYUg+zzY+AmLyVhgnb6jygbL1hQ65MQR5+YdSSA
        32SQfBSj+r2hwa+zFOKSBzPqmmdWPvI2tMHIJB5+GB3KeiDoaqXJOy2h+UKtsnWB
        TU3BuH02xtI16nIrdlklMUZF81p64KNhNEohwQIDAQABAoIBAC1U3YOIyY5Y9O4n
        yT2jn/sO2cs9s/rMgrbA4n0bM+FnVnqUDOWC2NDGoihqe4VKIzzmjs5c1CoSB+K3
        +NerCpOJGzyzdubWvhS9KfzGLjxG5g/CKut6l7yeK78h0aJn4thM9NncK/BqhmET
        nrsmpPwkd1yFe5fna3+irTtYcvWZgxp8DK4JxIRB0QpJvEwbs9fUFE1E0DVw/uBV
        CytTIrik2O+n1m8S5xzsFXHXDjXT/TVNi3jtN12Oaj1avYZRP2q45RmcODhtHQIy
        4o0vqjyAmZb3jOcYysyXVwfyNreIH3Qn0/waflPkyaljMpa1OHVOCJFjh2Xl+aIc
        dQsME3kCgYEA4aXU2xb9SHew84/3ow6ZmBeYLm+7B8GUjDTe7HqLldtTUhlrJSdB
        SHZHZ/BXEQ126FnbfZ0IISkBjqVCQBw8MgjZAlaEIInDA1DRTLuOfrcyUD6PeSLi
        gVZHNYbR9MDnmJ3/So5HXiRy2rBWtLKwPlciqbwY+l3xYr2kP/QdCisCgYEA3LpB
        TBDTqp9j8QVvB/YjCakS+z+kgtO5HyMZO/uh6o9PRHrFQHwZA5y/MRrx9lxJ9zOd
        fqysKfA7fXs4VzNnRSnOfBmuDHF0HhlIgAShX/RnB94p9xnsQaMae/o2nXcknQng
        3qogvHWTo16GCJRE+YTmhA0QtvSlScJlTzHfqcMCgYAPRt/rWVoajufvBX85jeJ+
        NpK6Chx6gPOirm2tSvqqUagJdekYIdk8o61f7xil8ehsALFohronLJSLaMrcdkzp
        AkpW6y6U2V7XmaAh9szF7Xc9kY67H85//SxjBlauoGTNo1zGWm2ghQ01mxyzrSlb
        fyC8pxx1zuhpy/cT0V4p8wKBgQDb+EJaq+pFf9L5v5CHPqRsXDKucR5hwt4aScA8
        JumV+HvmovMw8Ht9PhjLty6rdg3AbY/nTe3FXcPrqYDcZj3kj2VYB7+MZwRxeoDm
        E7c/CTIkhSMNPqhUQVeDdjg3dSTn25BeVu2I4yPfC7RHmHukru2La/ncWrLebvzH
        j8x2QQKBgQDevjRDDTWbBkg8HdCRxxCvhfaHBntoSJdTHlr14Gce48NXGaXRJPQT
        9dMsPsSHkFxEra7G2clGnhpe+pK9V+WTrD9Qnoc+tK808hX1YQ6mBlnR6w99jlaR
        HVTi2pRhEhbWUkBv2kooXvD6ANb15PbPSF1FK7YyW1KHqcbm+lF22g==
        -----END RSA PRIVATE KEY-----
    metron_agent:
      zone: z1
    networks:
      apps: default
    router:
      servers:
        z1:
        - 10.244.0.22
        z2: []
  resource_pool: default
  templates:
  - name: haproxy
    release: routing
  - name: metron_agent
    release: lamb
  - name: consul_agent
    release: consul
- instances: 1
  name: router_z1
  networks:
  - name: default
    static_ips:
    - 10.244.0.22
  properties:
    consul:
      agent:
        services:
          gorouter: {}
    metron_agent:
      zone: z1
    networks:
      apps: default
  resource_pool: default
  templates:
  - name: gorouter
    release: routing
  - name: metron_agent
    release: lamb
  - name: consul_agent
    release: consul
  update: {}
name: routing
networks:
- name: compilation
  subnets:
  - cloud_properties: {}
    range: 10.244.1.0/30
    reserved:
    - 10.244.1.1
  - cloud_properties: {}
    range: 10.244.1.4/30
    reserved:
    - 10.244.1.5
  - cloud_properties: {}
    range: 10.244.1.8/30
    reserved:
    - 10.244.1.9
  - cloud_properties: {}
    range: 10.244.1.12/30
    reserved:
    - 10.244.1.13
  - cloud_properties: {}
    range: 10.244.1.16/30
    reserved:
    - 10.244.1.17
  - cloud_properties: {}
    range: 10.244.1.20/30
    reserved:
    - 10.244.1.21
  - cloud_properties: {}
    range: 10.244.1.24/30
    reserved:
    - 10.244.1.25
  - cloud_properties: {}
    range: 10.244.1.28/30
    reserved:
    - 10.244.1.29
  - cloud_properties: {}
    range: 10.244.1.32/30
    reserved:
    - 10.244.1.33
  - cloud_properties: {}
    range: 10.244.1.36/30
    reserved:
    - 10.244.1.37
  - cloud_properties: {}
    range: 10.244.1.40/30
    reserved:
    - 10.244.1.41
  - cloud_properties: {}
    range: 10.244.1.44/30
    reserved:
    - 10.244.1.45
- name: default
  subnets:
  - cloud_properties: {}
    range: 10.244.0.20/30
    reserved:
    - 10.244.0.21
    static:
    - 10.244.0.22
  - cloud_properties: {}
    range: 10.244.0.32/30
    reserved:
    - 10.244.0.33
    static:
    - 10.244.0.34
  - cloud_properties: {}
    range: 10.244.0.72/30
    reserved:
    - 10.244.0.73
  - cloud_properties: {}
    range: 10.244.0.76/30
    reserved:
    - 10.244.0.77
properties:
  consul:
    agent:
      log_level: null
      servers:
        lan:
        - 10.244.0.54
  domain: 10.244.0.34.xip.io
  etcd:
    machines:
    - 10.244.0.42
  loggregator_endpoint:
    shared_secret: PLACEHOLDER-LOGGREGATOR-SECRET
  metron_agent:
    deployment: foo
  nats:
    machines:
    - 10.244.0.6
    password: nats
    port: 4222
    user: nats
  request_timeout_in_seconds: 900
  router:
    cipher_suites: null
    enable_ssl: null
    requested_route_registration_interval_in_seconds: null
    secure_cookies: null
    ssl_cert: null
    ssl_key: null
    ssl_skip_validation: true
    status:
      password: router
      user: router
  ssl:
    skip_cert_verify: true
  system_domain: 10.244.0.34.xip.io
  uaa:
    clients:
      gorouter:
        secret: gorouter-secret
releases:
- name: routing
  version: latest
- name: lamb
  version: latest
- name: consul
  version: latest
resource_pools:
- cloud_properties: {}
  name: default
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 50
  serial: true
  update_watch_time: 1000-180000

